In [1]:
import pandas as pd

In [2]:
info = {
    "name" : ["nahin", "fahim", "sid"],
    "cgpa" : [3.7, 3.5, 3.8]
}

df = pd.DataFrame(info)
print (df)

    name  cgpa
0  nahin   3.7
1  fahim   3.5
2    sid   3.8

In [3]:
df

    name  cgpa
0  nahin   3.7
1  fahim   3.5
2    sid   3.8

In [4]:
s = pd.Series([1,2,3,4,5])

print (s, type(s))
print (s[1])

0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.Series'>
2

In [5]:
s = pd.Series([23,24,25,26], index = ["nahin", "sid", "rony", "fahim"])

print (s)
print (s["fahim"])
print (s["nahin"])
print (s.index)

nahin    23
sid      24
rony     25
fahim    26
dtype: int64
26
23
Index(['nahin', 'sid', 'rony', 'fahim'], dtype='str')

In [6]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])

print (s1 + s2)

s1[0] = 100

change_s1 = s1.drop(0)

print (s1)
print (change_s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [10]:
#dataframe

info = {
    "name": ["fahim", "monjur", "sid"],
    "age": [23,24,25],
    "cgpa":[3.5, 3.6, 3.7]
}

df = pd.DataFrame(info)
df

     name  age  cgpa
0   fahim   23   3.5
1  monjur   24   3.6
2     sid   25   3.7